services:
  asr_service:
    runtime: nvidia
    restart: "unless-stopped"
    build:
      context: ../../
      dockerfile: ./services/asr/cuda.Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ../../services/asr/models:/app/models
      - ../../services/asr/Rocket.toml:/app/Rocket.toml:z
