services:
  auth_service:
    restart: "unless-stopped"
    build:
      context: ../../
      dockerfile: ./services/auth/Dockerfile
    ports:
      - "8010:8010"
    volumes:
      - ../../services/auth/config.toml:/app/services/auth/config.toml:ro
      - ../../services/auth/keys:/app/services/auth/keys:ro
      - ../../services/auth/auth.db:/app/services/auth/auth.db:z
