services:
  document_service:
    restart: "unless-stopped"
    build:
      context: ../../
      dockerfile: ../services/document/Dockerfile
    ports:
      - "8003:8003"
    volumes:
      - ../../services/document/Rocket.toml:/app/Rocket.toml:ro
