llm_continue_url="http://localhost:8013/api/v1/generate-continuation-hint"
skip_model_download=false

max_silence = 7.5
checked_sentences = 5
sentence_similarity_threshold = 0.95
repeated_sentence_threshold = 2

[store]
type="local"
path="../storage"
