include:
  - docker/rabbitmq.yml
  - docker/seaweedfs.yml
  - docker/gateway.yml

  # to run local version change path to docker/dev/<name>
  - docker/asr.yml
  - docker/auth.yml
  - docker/biometric.yml
  - docker/document.yml
  - docker/game.yml
  - docker/sds.yml
  - docker/stuck_detection.yml
  - docker/transcript_analysis.yml
  - docker/llm.yml
