include:
  - compose/rabbitmq.yml
  - compose/seaweedfs.yml
services:
  asr_service:
    runtime: nvidia
    build:
      context: .
      dockerfile: ./asr_service/Dockerfile

  document_service:
    build:
      context: .
      dockerfile: ./document_service/Dockerfile

  # auth_service:
  #   build:
  #     context: .
  #     dockerfile: ./auth_service/Dockerfile
  #   ports:
  #     - "8010:8010"
