[default]
address = "0.0.0.0"
port=8001

[default.asr]
backend="whisper"
model="Tiny"
vad="Silero"
model_dir="./models"
segment_buffer=4
silence_threshold=3

[default.recording_store]
type="local"
path="../storage"

[default.rabbitmq]
connection_name="game"
address="amqp://appuser:apppass@rabbitmq"
