rabbitmq_url = "amqp://appuser:apppass@rabbitmq"
llm_continue_url="http://llm_service:8013/api/v1/generate-continuation-hint"
max_silence = 7.5

checked_sentences = 5
sentence_similarity_threshold = 0.95
repeated_sentence_threshold = 2

[store]
type="s3"
endpoint="http://seaweedfs:8333"
bucket="cg-data"
access_key_id="admin_access_key"
secret_access_key="admin_secret_key"
