[project]
name = "stream-application"
version = "0.1.0"
description = ""
authors = [
    {name = "navindunimsara2001",email = "navidunimsara@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard] (>=0.122.0,<0.123.0)",
    "uvicorn (>=0.38.0,<0.39.0)",
    "whisperlivekit (>=0.2.16,<0.3.0)",
    "pika (>=1.3.2,<2.0.0)"
]

[tool.poetry]
package-mode = false


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
