[default]
address = "0.0.0.0"
port=8000
recording_dir="../recordings"

[default.model]
model="Small"
vad="Silero"
model_dir="./models"
segment_buffer=4

[default.recording_store]
type="local"
path="/tmp"
