[default]
address = "0.0.0.0"
port=8000

[default.asr]
backend="whisper"
model="Tiny"
vad="Silero"
model_dir="./models"
segment_buffer=4
silence_threshold=3

[default.recording_store]
type="local"
path="../store"
