events {}

http {
    upstream auth_service {
        server auth_service:8010;
    }

    upstream document_service {
        server document_service:8003;
    }

    upstream game_service {
        server game_service:8004;
    }

    upstream llm_service {
        server llm_service:8013;
    }

    upstream seaweedfs {
        server seaweedfs:8333;
    }

    upstream transcript_analysis_service {
        server transcript_analysis_service:8005;
    }

    upstream sds {
        server sds_service:8006;
    }

    server {
        listen 80;

        # Auth service
        location /api/auth/ {
            proxy_pass http://auth_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_redirect off;
        }

        # Document upload
        location /api/document/upload/ {
            proxy_pass http://document_service/upload/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_redirect off;
        }

        # WebSocket game service
        location /api/ws/ {
            proxy_pass http://game_service/ws/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_buffering off;
            proxy_read_timeout 3600s;
        }

        location /api/internal/llm/ {
            proxy_pass http://llm_service/api/v1/;
        }

        location /api/internal/analyze_transcript {
            proxy_pass http://transcript_analysis_service/;
        }

        location /api/internal/speech_score/ {
            proxy_pass http://sds_service/analyze-speech;
        }

        location /api/internal/s3/ {
            proxy_pass http://seaweedfs/;
        }


    }
}
