[default]
address = "0.0.0.0"
port=8001

[default.asr]
backend="whisper"
model="Tiny"
vad="Silero"
model_dir="./models"
segment_buffer=4
silence_threshold=3

[default.recording_store]
type="local"
path="../storage"

[default.rabbitmq]
connection_name="game"
address="amqp://appuser:apppass@127.0.0.1"

[release.rabbitmq]
address="amqp://appuser:apppass@rabbitmq"

[release.recording_store]
type="s3"
endpoint="http://seaweedfs:8333"
bucket="cg-data"
access_key_id="admin_access_key"
secret_access_key="admin_secret_key"
