services:
  asr_service:
    image: ghcr.io/cognivox-research/asr_service_cuda:v0.1.1
    runtime: nvidia
    restart: "unless-stopped"
    ports:
      - "8001:8001"

    build:
      context: ../
      dockerfile: ./services/asr/Dockerfile

    depends_on:
      rabbitmq:
        condition: service_healthy

    volumes:
      - ../services/asr/models:/app/models
      - ../services/asr/Rocket.toml:/app/Rocket.toml:z

    env_file: ../.env.template
