services:
  document_service:
    image: ghcr.io/cognivox-research/document_service:v0.0.3
    restart: "unless-stopped"
    build:
      context: ..
      dockerfile: ./services/document/Dockerfile

    ports:
      - "8003:8003"

    volumes:
      - ../services/document/Rocket.toml:/app/Rocket.toml:ro

    env_file: ../.env.template
