services:
  document_service:
    image: ghcr.io/cognivox-research/document_service:v0.0.1
    restart: "unless-stopped"
    ports:
      - "8003:8003"
    volumes:
      - ../services/document/Rocket.toml:/app/Rocket.toml:ro
