services:
  game_service:
    image: ghcr.io/cognivox-research/game_service:v0.0.1
    restart: "unless-stopped"
    ports:
      - "8004:8004"
    volumes:
      - ../services/game/Rocket.toml:/app/Rocket.toml:ro
      - ../services/auth/keys/public.pem:/app/public.pem:ro
