services:
  sds_service:
    image: ghcr.io/cognivox-research/sds_service:v0.0.3
    restart: "unless-stopped"
    build:
      context: ../
      dockerfile: ./services/sds/Dockerfile
    ports:
      - "8006:8006"
    volumes:
      - ./config/sds.toml:/app/services/sds/config.toml:ro

    env_file: ../.env.template
