services:
  stuck_detection_service:
    image: ghcr.io/cognivox-research/stuck_detection_service:v0.0.1
    restart: "unless-stopped"
    ports:
      - "8012:8012"
    volumes:
      - ./config/stuck_detection.toml:/app/services/stuck_detection/config.toml:ro
      - ../services/stuck_detection/models:/app/models
