/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AppSessionRouteImport } from './routes/app/session'
import { Route as AppSessionStartRouteImport } from './routes/app/session/start'
import { Route as AppSessionOptionsRouteImport } from './routes/app/session/options'
import { Route as AppSessionDocumentRouteImport } from './routes/app/session/document'
import { Route as AppSessionIdRouteImport } from './routes/app/session/$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppSessionRoute = AppSessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionStartRoute = AppSessionStartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => AppSessionRoute,
} as any)
const AppSessionOptionsRoute = AppSessionOptionsRouteImport.update({
  id: '/options',
  path: '/options',
  getParentRoute: () => AppSessionRoute,
} as any)
const AppSessionDocumentRoute = AppSessionDocumentRouteImport.update({
  id: '/document',
  path: '/document',
  getParentRoute: () => AppSessionRoute,
} as any)
const AppSessionIdRoute = AppSessionIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppSessionRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/app/session': typeof AppSessionRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/app/session/$id': typeof AppSessionIdRoute
  '/app/session/document': typeof AppSessionDocumentRoute
  '/app/session/options': typeof AppSessionOptionsRoute
  '/app/session/start': typeof AppSessionStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/app/session': typeof AppSessionRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/app/session/$id': typeof AppSessionIdRoute
  '/app/session/document': typeof AppSessionDocumentRoute
  '/app/session/options': typeof AppSessionOptionsRoute
  '/app/session/start': typeof AppSessionStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/app/session': typeof AppSessionRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/app/session/$id': typeof AppSessionIdRoute
  '/app/session/document': typeof AppSessionDocumentRoute
  '/app/session/options': typeof AppSessionOptionsRoute
  '/app/session/start': typeof AppSessionStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/session'
    | '/auth/login'
    | '/auth/register'
    | '/app/session/$id'
    | '/app/session/document'
    | '/app/session/options'
    | '/app/session/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/auth'
    | '/app/session'
    | '/auth/login'
    | '/auth/register'
    | '/app/session/$id'
    | '/app/session/document'
    | '/app/session/options'
    | '/app/session/start'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/session'
    | '/auth/login'
    | '/auth/register'
    | '/app/session/$id'
    | '/app/session/document'
    | '/app/session/options'
    | '/app/session/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/app/session': {
      id: '/app/session'
      path: '/session'
      fullPath: '/app/session'
      preLoaderRoute: typeof AppSessionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/session/start': {
      id: '/app/session/start'
      path: '/start'
      fullPath: '/app/session/start'
      preLoaderRoute: typeof AppSessionStartRouteImport
      parentRoute: typeof AppSessionRoute
    }
    '/app/session/options': {
      id: '/app/session/options'
      path: '/options'
      fullPath: '/app/session/options'
      preLoaderRoute: typeof AppSessionOptionsRouteImport
      parentRoute: typeof AppSessionRoute
    }
    '/app/session/document': {
      id: '/app/session/document'
      path: '/document'
      fullPath: '/app/session/document'
      preLoaderRoute: typeof AppSessionDocumentRouteImport
      parentRoute: typeof AppSessionRoute
    }
    '/app/session/$id': {
      id: '/app/session/$id'
      path: '/$id'
      fullPath: '/app/session/$id'
      preLoaderRoute: typeof AppSessionIdRouteImport
      parentRoute: typeof AppSessionRoute
    }
  }
}

interface AppSessionRouteChildren {
  AppSessionIdRoute: typeof AppSessionIdRoute
  AppSessionDocumentRoute: typeof AppSessionDocumentRoute
  AppSessionOptionsRoute: typeof AppSessionOptionsRoute
  AppSessionStartRoute: typeof AppSessionStartRoute
}

const AppSessionRouteChildren: AppSessionRouteChildren = {
  AppSessionIdRoute: AppSessionIdRoute,
  AppSessionDocumentRoute: AppSessionDocumentRoute,
  AppSessionOptionsRoute: AppSessionOptionsRoute,
  AppSessionStartRoute: AppSessionStartRoute,
}

const AppSessionRouteWithChildren = AppSessionRoute._addFileChildren(
  AppSessionRouteChildren,
)

interface AppRouteChildren {
  AppSessionRoute: typeof AppSessionRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppSessionRoute: AppSessionRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
