/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AppSessionRouteImport } from './routes/app/session'
import { Route as AppSessionPlayRouteImport } from './routes/app/session/play'
import { Route as AppSessionNewRouteImport } from './routes/app/session/new'
import { Route as AppSessionNewStartRouteImport } from './routes/app/session/new/start'
import { Route as AppSessionNewOptionsRouteImport } from './routes/app/session/new/options'
import { Route as AppSessionNewDocumentRouteImport } from './routes/app/session/new/document'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppSessionRoute = AppSessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionPlayRoute = AppSessionPlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => AppSessionRoute,
} as any)
const AppSessionNewRoute = AppSessionNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppSessionRoute,
} as any)
const AppSessionNewStartRoute = AppSessionNewStartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => AppSessionNewRoute,
} as any)
const AppSessionNewOptionsRoute = AppSessionNewOptionsRouteImport.update({
  id: '/options',
  path: '/options',
  getParentRoute: () => AppSessionNewRoute,
} as any)
const AppSessionNewDocumentRoute = AppSessionNewDocumentRouteImport.update({
  id: '/document',
  path: '/document',
  getParentRoute: () => AppSessionNewRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/app/session': typeof AppSessionRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/app/session/new': typeof AppSessionNewRouteWithChildren
  '/app/session/play': typeof AppSessionPlayRoute
  '/app/session/new/document': typeof AppSessionNewDocumentRoute
  '/app/session/new/options': typeof AppSessionNewOptionsRoute
  '/app/session/new/start': typeof AppSessionNewStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/app/session': typeof AppSessionRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/app/session/new': typeof AppSessionNewRouteWithChildren
  '/app/session/play': typeof AppSessionPlayRoute
  '/app/session/new/document': typeof AppSessionNewDocumentRoute
  '/app/session/new/options': typeof AppSessionNewOptionsRoute
  '/app/session/new/start': typeof AppSessionNewStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/app/session': typeof AppSessionRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/app/session/new': typeof AppSessionNewRouteWithChildren
  '/app/session/play': typeof AppSessionPlayRoute
  '/app/session/new/document': typeof AppSessionNewDocumentRoute
  '/app/session/new/options': typeof AppSessionNewOptionsRoute
  '/app/session/new/start': typeof AppSessionNewStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/session'
    | '/auth/login'
    | '/auth/register'
    | '/app/session/new'
    | '/app/session/play'
    | '/app/session/new/document'
    | '/app/session/new/options'
    | '/app/session/new/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/auth'
    | '/app/session'
    | '/auth/login'
    | '/auth/register'
    | '/app/session/new'
    | '/app/session/play'
    | '/app/session/new/document'
    | '/app/session/new/options'
    | '/app/session/new/start'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/session'
    | '/auth/login'
    | '/auth/register'
    | '/app/session/new'
    | '/app/session/play'
    | '/app/session/new/document'
    | '/app/session/new/options'
    | '/app/session/new/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/app/session': {
      id: '/app/session'
      path: '/session'
      fullPath: '/app/session'
      preLoaderRoute: typeof AppSessionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/session/play': {
      id: '/app/session/play'
      path: '/play'
      fullPath: '/app/session/play'
      preLoaderRoute: typeof AppSessionPlayRouteImport
      parentRoute: typeof AppSessionRoute
    }
    '/app/session/new': {
      id: '/app/session/new'
      path: '/new'
      fullPath: '/app/session/new'
      preLoaderRoute: typeof AppSessionNewRouteImport
      parentRoute: typeof AppSessionRoute
    }
    '/app/session/new/start': {
      id: '/app/session/new/start'
      path: '/start'
      fullPath: '/app/session/new/start'
      preLoaderRoute: typeof AppSessionNewStartRouteImport
      parentRoute: typeof AppSessionNewRoute
    }
    '/app/session/new/options': {
      id: '/app/session/new/options'
      path: '/options'
      fullPath: '/app/session/new/options'
      preLoaderRoute: typeof AppSessionNewOptionsRouteImport
      parentRoute: typeof AppSessionNewRoute
    }
    '/app/session/new/document': {
      id: '/app/session/new/document'
      path: '/document'
      fullPath: '/app/session/new/document'
      preLoaderRoute: typeof AppSessionNewDocumentRouteImport
      parentRoute: typeof AppSessionNewRoute
    }
  }
}

interface AppSessionNewRouteChildren {
  AppSessionNewDocumentRoute: typeof AppSessionNewDocumentRoute
  AppSessionNewOptionsRoute: typeof AppSessionNewOptionsRoute
  AppSessionNewStartRoute: typeof AppSessionNewStartRoute
}

const AppSessionNewRouteChildren: AppSessionNewRouteChildren = {
  AppSessionNewDocumentRoute: AppSessionNewDocumentRoute,
  AppSessionNewOptionsRoute: AppSessionNewOptionsRoute,
  AppSessionNewStartRoute: AppSessionNewStartRoute,
}

const AppSessionNewRouteWithChildren = AppSessionNewRoute._addFileChildren(
  AppSessionNewRouteChildren,
)

interface AppSessionRouteChildren {
  AppSessionNewRoute: typeof AppSessionNewRouteWithChildren
  AppSessionPlayRoute: typeof AppSessionPlayRoute
}

const AppSessionRouteChildren: AppSessionRouteChildren = {
  AppSessionNewRoute: AppSessionNewRouteWithChildren,
  AppSessionPlayRoute: AppSessionPlayRoute,
}

const AppSessionRouteWithChildren = AppSessionRoute._addFileChildren(
  AppSessionRouteChildren,
)

interface AppRouteChildren {
  AppSessionRoute: typeof AppSessionRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppSessionRoute: AppSessionRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
